baseURL = "https://ditz3n.github.io/CREAMi/"
languageCode = "da-dk"
title = "Ditz3n's Ninja CREAMi Laboratorium"
theme = "PaperMod"
contentDir = "content"

[params]
    defaultTheme = "dark"
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowReadingTime = false

[menu]
  [[menu.main]]
    identifier = "recipes"
    name = "Opskrifter"
    url = "/recipes/"
    weight = 10 # Juster 'weight' for at ændre rækkefølgen (lavere tal er først)
  [[menu.main]]
    identifier = "calculator"
    name = "Udregner"
    url = "/calculator/"
    weight = 15
  [[menu.main]]
    identifier = "stabilizer"
    name = "Stabilizer"
    url = "/stabilizer/"
    weight = 20
  [[menu.main]]
    identifier = "ingredients"
    name = "Ingrediensdatabase"
    url = "/ingredients/"
    weight = 25

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true